#default_language_version:
python: python3.9

default_stages: [commit, push]

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: trailing-whitespace
  - id: check-ast

- repo: https://github.com/psf/black
  rev: 23.10.0
  hooks:
  - id: black


- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort


-   repo: local
    hooks:
    -   id: pylint-score-check
        args: ['--disable=too-few-public-methods,no-self-use','--ignore=api/v1/tests/']
        name: Pylint Score Check
        entry: ./api/pylint_score_check.sh
        language: script
        types: [python]
        exclude: '^api/v1/tests/'